pollme/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home ,name='home'),
    path('poll/', include('polls.urls',namespace='poll'))
]

polls/urls.py
from django.urls import path
from . import views
app_name='poll'
urlpatterns = [
    path('list/', views.poll_list, name='list'),
    #polls/details/1 ===>
    path('details/<int:poll_id>/', views.poll_detail, name='detail'),
    #polls/details/1/vote ===>
    path('details/<int:poll_id>/vote/', views.poll_vote, name='vote')

]

polls/models.py
from django.db import models

# Create your models here.
class Polls(models.Model):
    text=models.CharField(max_length=255)
    pub_date=models.DateField()

    def __str__(self):
        return self.text


class Choice(models.Model):
    question=models.ForeignKey(Polls,on_delete=models.CASCADE)
    choice_text=models.CharField(max_length=255)
    votes=models.IntegerField(default=0)

    def __str__(self):
        return '{} - {}'.format(self.question.text[:20],self.choice_text[:20])

pollme/views.py
from django.shortcuts import render



def home(request):

    context={}
    return render(request,'home.html',context)

polls/views.py
from django.contrib import messages #lec 33
from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse #lec 34
from .models import Choice,Polls

# Create your views here.
def poll_list(request):
    polls=Polls.objects.all()
    return render(request,'polls/list.html',{'polls':polls})
'''
showing the polls saved in the admin page for now we
have 2 polls in the admin panel if we put 1 or 2 on browser besided the details url
we have get the two sentance( for every santance ) we entered in the model in admin panel
if we put 3 or more like 4,5,6,...etc we will have an error becuse this
doesnt matched in the Polls class
    pass
'''


def poll_detail(request, poll_id):
    #poll=Polls.objects.get(id=poll_id)
    poll=get_object_or_404(Polls,id=poll_id)
    '''
    lec 29
    the next 6 line its just for testing the post and get
    when we want to check the get from termanal we just add
    to browser link --> exampel like this(?name='join'&age=9) beside our url
    '''
    if request.method =="POST":
        print(request.POST)
        print("you post")


    if request.method =="GET":
        print(request.GET)
        print("you Got ME")

    context={'poll':poll}
    return render(request, 'polls/poll_detail.html',context)
    #return HttpResponse('the url is : {}'.format(poll_id))


def poll_vote(request,poll_id):
    #print(request.POST) #print the query in cmd terminal
    #print('Sparator ************************')# print statment just for sparate the sentance above and below
    #choice_id=request.POST['choice'] # lec 30 give the choice readable value from the poll_detail.html in the form that have post method
    #print(choice_id)# print the location of choice in [] function its 1 in the cmd termanal
    poll=get_object_or_404(Polls,id=poll_id) #lec 33
    choice_id=request.POST.get('choice')#add in lec 31
    if choice_id: # to check the choice if we have >> save the votes
        choice = Choice.objects.get(id=choice_id)#grap the content of choice_id
        #poll = choice.question # lec 32
        #print(choice)#print the value of chioce parameter we decleare
        choice.votes += 1 # (call votes parameter from the models.py)incremment the vote --> plus vote
        choice.save()# save the vote we add in the above decleare>> then test that by admin page -- add vote by browser then check the admin page
    else: #lec 33
        messages.error(request,'thies in no Choice') #lec 33
        return HttpResponseRedirect(reverse('poll:detail', args=(poll_id,))) #lec 34 to reverse error msg in the same of the page ==> detail page
        #return HttpResponse('the vote is:{}'.format(poll_id))
    return render(request,'polls/poll_results.html', {'poll':poll}) #lec  32
    #lec 31 if we not have a vote print the next HttpResponse
    #return HttpResponse('theres no votes'.format(poll_id))
    #return render(request,'polls/poll_results.html',{'error':True}) #lec 32




'''
# NOTE: the print statment in the views.py just print there result in cmd compiler
we can ignor it from our views.py

'''

polls/templates/polls/list.html
{% extends 'base_layout.html' %}
{% block content %}
<div class="container">
  <h1>welcom to the poll list </h1>
  <ul>
    {% for poll in polls%}
    <li><a href="{% url 'poll:detail' poll.id %}">{{ poll }}</a></li>
     <ul>
       {% for choice in poll.choice_set.all %}
         <li>{{ choice.choice_text}}</li>

       {% endfor %}
     </ul>
    {% endfor %}
  </ul>
</div>
{% endblock %}

polls/templates/polls/poll_detail.html
{% extends 'base_layout.html' %}

{% block content %}

                                                                      {%comment%}
                                                                      from lec 34
                                                                      {% if messages %}
                                                                        <ul class="messages">
                                                                            {% for message in messages %}
                                                                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                                                            {% endfor %}
                                                                        </ul>
                                                                        {% endif %}
                                                                      {% endcomment%}


{% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}


<h1>Welcome to the poll details </h1>
  {{poll}}
                                                  {%comment%}
                                                   we add action in <form  action="index.html"> this page we want to go to it
                                                     in the form benath
                                                  {% endcomment%}

  <form action="{% url 'poll:vote' poll.id %}" method="post">
    {% csrf_token %}
    {% for choice in poll.choice_set.all %}
      <input type="radio" name="choice" id="choice {{forloop.counter}}" value="{{ choice.id }}">

      <label for="choice {{ forloop.counter }}" > {{ choice.choice_text}}</label>
      <br>
    {%endfor%}
    <input type="submit" value="vote">
  </form>
{% endblock %}

polls/templates/polls/poll_results.html
{% extends 'base_layout.html' %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col">


                                                                                                  {%comment%}
                                                                                                  from lec 32
                                                                                                  {% if error %}
                                                                                                    <h1>ERROR / NO voets</h1>
                                                                                                  {% else %}
                                                                                                  {% endcomment%}

        {% if messages %}
          <ul class="messages">
              {% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
              {% endfor %}
          </ul>
          {% endif %}
           <ul>
            {% for choice in poll.choice_set.all %}
              <li>{{ choice.choice_text }} -- {{choice.votes}}</li>
            {% endfor %}
          </ul>

      </div>
    </div>

  </div>
{% endblock %}

templates/base_layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title> Polls List</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
          crossorigin="anonymous">

    {% block custom_css %}{% endblock %}
  </head>
  <body>

    {% include 'include/navbar.html' %}

    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
            integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
            crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base_layout.html' %}
{% load static %}
{% block custom_css %}
    <link rel="stylesheet" href="{% static 'css/home_styles.css' %}" type="text/css">
{% endblock %}

{% block content %}

  <div class="container">
    <div class="row">
      <div class="cal">
        <div id="home-content">
          <h1>PollMe - Get stared</h1>
          <h3> Welcome To Home Page</h3>
          <hr>
          <button type="button" class="btn btn-light btn-lg">Get Started!</button>
        </div>
      </div>
    </div>

  </div>


   <button type="button" class="btn btn-danger">Action</button>


{% endblock %}

templates/include/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
 <a class="navbar-brand" href="#">Navbar</a>
 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
 </button>
 <div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'poll:list' %}">polls</a>
    </li>


  </ul>
 </div>
</nav>